pipeine:
  build:
    image: alpine
    commands:
      - echo hello
  test:
    image: alpine
    commands: echo $DRONE_SECRET

clone:
  default:
    image: alpine
    commands:
      - echo $DRONE_REPO_PRIVATE
      - cat /root/.netrc

